Added basic functionality
Grechukha/RollBall pull request #1
Opened 2019-12-20 14:10 UTC by Grechukha

2019-12-22 19:02 UTC, HolyMonkey requested changes

2019-12-22 19:02 UTC, HolyMonkey commented on Assets/Scripts/Boundary.cs
> +        var isRemovableObject = !collision.gameObject.GetComponent<GroundPlatform>() && !collision.gameObject.GetComponent<PlayerMovement>();
Испольузуй == false вместо !

2019-12-22 19:02 UTC, HolyMonkey commented on Assets/Scripts/CameraTracking.cs
> +        _offset = new Vector3(_camera.orthographicSize * _camera.aspect * 0.66f, 0, 0);
Почему 0.66?

Смотри антипатерн "Магическое число"

2019-12-22 19:02 UTC, HolyMonkey commented on Assets/Scripts/CoinSpawner.cs
> +    [SerializeField] private int _countOfCoins;
Старайся не использовать of
_coinsCount 
или даже просто 
_targetCount

2019-12-22 19:02 UTC, HolyMonkey commented on Assets/Scripts/CoinSpawner.cs
> +        if (Time.time > _nextSpawn)
Почему эта проверка не в базовом классе?

2019-12-22 19:02 UTC, HolyMonkey commented on Assets/Scripts/CoinSpawner.cs
> +    private Vector3 _coinPosition;
_nextCoinPosition

2019-12-22 19:02 UTC, HolyMonkey commented on Assets/Scripts/CoinSpawner.cs
> +            Mathf.Clamp(_coinPosition.y, -transform.localScale.y + transform.position.y, transform.localScale.y + transform.position.y);
Это лучше заменить на детерменированный алгоритм 

Vector3 GetCoinPosition(int number)

2019-12-22 19:02 UTC, HolyMonkey commented on Assets/Scripts/GroundChecker.cs
> +    }
Используй автореализуемое свойство с запреваченным сетером

2019-12-22 19:02 UTC, HolyMonkey commented on Assets/Scripts/GroundChecker.cs
> +    private void OnCollisionStay2D(Collision2D collision)
Здесь будет достаточно Enter

2019-12-22 19:02 UTC, HolyMonkey commented on Assets/Scripts/GroundPlatform.cs
> +    }
Сократи до 
public Transform StartPoint => _startPoint;

2019-12-22 19:02 UTC, HolyMonkey commented on Assets/Scripts/MainMenu.cs
> +    public void Exid()
Exit

2019-12-22 19:02 UTC, HolyMonkey commented on Assets/Scripts/MainMenu.cs
> +    public void Exid()
Так как это обработчики кнопок, то их стоит называть как обработчики

PlayButtonClickHandler 

И т.д

2019-12-22 19:02 UTC, HolyMonkey commented on Assets/Scripts/PlayerMovement.cs
> +    private float _storeMaxJumpTime;
_originalMaxJumpTime

2019-12-22 19:02 UTC, HolyMonkey commented on Assets/Scripts/Spawner.cs
> +            _nextSpawn = Time.time + Random.Range(_minDelay, _maxDelay);
Вот должен быть вызов абстрактного метода который переопределяет PlatformsSpawner и CoinsSpawner

2019-12-22 20:31 UTC, Grechukha commented on Assets/Scripts/GroundChecker.cs
> +    private void OnCollisionStay2D(Collision2D collision)
При Enter, почему то, иногда не срабатывает. Шарик катится, но прыгнуть не получается

2019-12-25 22:19 UTC, HolyMonkey requested changes

2019-12-25 22:19 UTC, HolyMonkey commented on Assets/Scripts/Boundary.cs
> +            && (collision.gameObject.GetComponent<PlayerMovement>() == false);
Длинная строка и её трудно редактировать. Выдели её в метод а там разбей на кучку if'ов или подумай просто работать с массивом типов и просто задачей их через массив в начале компонента

2019-12-25 22:19 UTC, HolyMonkey commented on Assets/Scripts/CameraTracking.cs
> +
Лишняя строка

2019-12-25 22:19 UTC, HolyMonkey commented on Assets/Scripts/CameraTracking.cs
> +    private Camera _camera;
отдели группу полей без аттрибута пустой строкой

2019-12-25 22:19 UTC, HolyMonkey commented on Assets/Scripts/CameraTracking.cs
> +
А вот тут одна строка лишняя пустая

2019-12-25 22:19 UTC, HolyMonkey commented on Assets/Scripts/CameraTracking.cs
> +    [SerializeField] private Vector3 _startPositin = new Vector3(0, 2, -10);
В чём смысл? Почему бы просто камеру на поставить в начале в эту точку?

2019-12-25 22:19 UTC, HolyMonkey commented on Assets/Scripts/CoinsHolder.cs
> +    [SerializeField] private TMP_Text CountOfCoinsText;
Нарушена стилистика именования

2019-12-25 22:19 UTC, HolyMonkey commented on Assets/Scripts/GroundChecker.cs
> +    }
Тут должно быть не свойство. Это метод в первую очередь

2019-12-27 13:33 UTC, HolyMonkey requested changes

2019-12-27 13:33 UTC, HolyMonkey commented on Assets/Scripts/CameraTracking.cs
> +        _offset = new Vector3(_camera.orthographicSize * _camera.aspect * -_offsetRelativeCenterCameraX, 0, 0);
Нет смысла хранить данные в поле. Метод должен сразу их возвращать

2019-12-27 13:33 UTC, HolyMonkey commented on Assets/Scripts/MainMenu.cs
> +    public void PlayButtonClickHandler(string level)
Прости мы пересмотрели стандарты на эту тему - https://trello.com/b/aerR0R28/unity

2019-12-27 13:33 UTC, HolyMonkey commented on Assets/Scripts/PlatformShifter.cs
> +    private void ShiftPlatformsArray()
Array тут лишнее

2019-12-27 13:33 UTC, HolyMonkey commented on Assets/Scripts/PlatformShifter.cs
> +        GroundPlatform tempGroundPlatform = _groundPlatforms[0];
firstPlatform

2019-12-27 13:33 UTC, HolyMonkey commented on Assets/Scripts/PlatformShifter.cs
> +        for (int i = 0; i < _groundPlatforms.Length - 1; i++)
Вместо массива попробуй использовать очередь

2019-12-27 13:33 UTC, HolyMonkey commented on Assets/Scripts/PlatformShifter.cs
> +    [SerializeField] private GroundPlatform[] _groundPlatforms;
В данном случае если ты будешь использовать очередь то можешь взять все дочерние платформы по отношению к шифтеру

2019-12-27 13:33 UTC, HolyMonkey commented on Assets/Scripts/PlatformShifter.cs
> +        ShiftPlatformPosition();
Объедини эти два метода

2019-12-27 13:33 UTC, HolyMonkey commented on Assets/Scripts/Spawner.cs
> +public class Spawner : MonoBehaviour
Откажись от движения спавнера по сцене

2020-01-06 18:00 UTC, HolyMonkey requested changes

2020-01-06 18:00 UTC, HolyMonkey commented on Assets/Scripts/Boundary.cs
> +public class Boundary : MonoBehaviour
А зачем он удаляет объекты?

2020-01-06 18:00 UTC, HolyMonkey commented on Assets/Scripts/CoinsHolder.cs
> +    private int _countOfCoins;
_coins

2020-01-06 18:00 UTC, HolyMonkey commented on Assets/Scripts/CoinsHolder.cs
> +    [SerializeField] private TMP_Text _countOfCoinsText;
_coinsText

2020-01-06 18:00 UTC, HolyMonkey commented on Assets/Scripts/PlatformShifter.cs
> +public class PlatformShifter : MonoBehaviour
PlatformsShifter

2020-01-06 18:00 UTC, HolyMonkey commented on Assets/Scripts/PlatformShifter.cs
> +        Vector3 newPosition = _groundPlatforms.ToArray()[_groundPlatforms.Count - 1].EndPoint.position - firstPlatform.StartPoint.localPosition;
Давай вернёмся к массиву

2020-02-15 12:35 UTC, merged